### ISSUE TITLE
CiteScore dumps outdated

### ISSUE THREAD

**Issue by ravwojdyla** [dhimmel/scopus#5]
Example, from [metrics](https://github.com/dhimmel/scopus/blob/50171219c2b2261bd2529f8ca354e4ba25725626/data/metrics.tsv.gz):

```
21206   2016    CiteScore       13.33
21206   2016    SJR     18.13
21206   2016    SNIP    8.039
```

while https://www.scopus.com/sourceid/21206: for 2016 CiteScore is 49.2.

Looks like the score formula was updated and backfilled?

**Comment by dhimmel** [comment]
Ah good catch! I am guessing the change occurred with the 2019 release as per https://blog.scopus.com/posts/citescore-2019-now-live

> CiteScore 2019 has a new and enhanced methodology ... Longer citation window (4 years instead of 1 year).

So perhaps the longer citation window increases the score. The announcement also mentions:

> The new methodology will also be used to retrospectively calculated CiteScore values for all previous years (2011 – 2018) 

It would be nice to update this repo with the scores generated from the new methodology, although how much work that would be is a bit unknown. The data can be a bit messy so there is a chance the update brings new issues with it as well.

**Comment by dhimmel** [comment]
I was able to download the latest data at https://www.scopus.com/sources (after logging in), which included these two files:

- `CiteScore 2011-2020 new methodology - May 2021.xlsb`
- `extlistJuly2021.xlsx`

The format is largely similar to before, so updating would be possible. @ravwojdyla if the updated scores would be valuable for you, I can take a stab at this.

I do like how the scores would go back further in time (2011-2020)

**Comment by ravwojdyla** [comment]
@dhimmel thanks for a prompt response and help! Definitely not (time) critical for me.

**Comment by dhimmel** [comment]
With the new data in https://github.com/dhimmel/scopus/pull/6, we now see the expected CiteScores for _Nature_:

`zcat data/metrics.tsv.gz | grep 21206`

```
scopus_id       year    metric  value
21206   2011    CiteScore       53.1
21206   2011    SJR     17.6
21206   2011    SNIP    8.65
21206   2012    CiteScore       51
21206   2012    SJR     17.5
21206   2012    SNIP    8.41
21206   2013    CiteScore       50.9
21206   2013    SJR     19.7
21206   2013    SNIP    8.48
21206   2014    CiteScore       49.9
21206   2014    SJR     18.8
21206   2014    SNIP    7.95
21206   2015    CiteScore       51.6
21206   2015    SJR     19.7
21206   2015    SNIP    8.05
21206   2016    CiteScore       49.2
21206   2016    SJR     18.4
21206   2016    SNIP    7.9
21206   2017    CiteScore       53.7
21206   2017    SJR     17.9
21206   2017    SNIP    8.65
21206   2018    CiteScore       55.7
21206   2018    SJR     16.3
21206   2018    SNIP    9.45
21206   2019    CiteScore       51
21206   2019    SJR     14
21206   2019    SNIP    8.82
21206   2020    CiteScore       56.9
21206   2020    SJR     16
21206   2020    SNIP    9.25
```

**Comment by dhimmel** [comment]
I didn't update the NLM journal list from `https://ftp.ncbi.nih.gov/pubmed/J_Medline.txt`, but might do this as well... but code is in a different repo
