### ISSUE TITLE
Use ISSN-L to improve journal mapping

### ISSUE THREAD

**Issue by tamunro** [dhimmel/scopus#7]
Sorry if this is a dumb newbie suggestion, but for matching journals in different datasets via ISSN, I think adding ISSN-Ls to each dataset, then matching on that, might catch more overlap. I've seen cases where WoS and Scopus have chosen different ISSNs for the same journal. The conversion table can be obtained here:
http://www.issn.org/services/online-services/access-to-issn-l-table/
or I suppose could be scraped from individual entries.

**Comment by dhimmel** [comment]
The [data/issn.tsv](https://github.com/dhimmel/scopus/blob/1c2f8aa0eb4738ced9923a773020427441aa521c/data/issn.tsv) file we extract from scopus contains Scopus journal to ISSN mappings. The ISSNs are coded as either `electronic` or `print`. From the link you provide, it appears that the ISSN-L corresponds to either the print or electronic ISSN and is not a new ISSN itself (although I haven't checked this exhaustively).

Given that Scopus sometimes provides multiple ISSNs per journal, do you still think it would improve mappings to go through ISSN-Ls?

**Comment by tamunro** [comment]
That's right, it matches one of the ISSNs. The advantage is that there's one and only one per journal, as with the Scopus and NLM IDs. Given that both NLM and Scopus seem to distinguish print and online ISSNs, it presumably wouldn't be needed in this case, but there may be cases where Scopus only has the online ISSN and pubmed only print, or vice versa. There can also be more than two, e.g. this one has seven different ISSNs, if you mouse over the icons:
https://portal.issn.org/resource/ISSN-L/0001-5393
So there's potential for different databases to end up choosing different ones. For pulling in information from other sources, e.g. WoS, Dimensions, DOAJ, I think ISSN-L would be worth considering. Perhaps something to keep in mind, anyway. They're criminally underutilized.

**Comment by dhimmel** [comment]
Nice explanation. Sounds like if we're using ISSNs to identify journals, we should always convert them to ISSN-Ls. I submitted the request.... a bit annoying that this mapping can't just be downloaded.

**Comment by dhimmel** [comment]
It took a few days and some email back and forth, but I was finally granted access to download `issnltables.zip`. Added the intermediate step to convert to linking ISSNs in https://github.com/dhimmel/scopus/pull/8. This created 134 additional mappings between NLM and Scopus journals (out of 20,011). So a small increase in mapping coverage.
